<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtml1v2joYx+8n9TswaVI67agy0JwuQlwQE4yTkjYOefPNlBfqhCQkWqCQfvrjUNa1OtLU7uxiZ/LPMpYdHj/2/3niC3Cv98iHL5yxVH/NNts7aXTsnhhLyzRrenGVrHq8XW3ir229XSXve7AIm+bi4kIanb07zdM7eyfK71i6iPZ+IeN/jUh+X2kCr59RpI2l49CzvHgVp7Qb9wQCgeDPRIpLFyS+vsPIHQTevtJnyp3f5lePp2Z3bB5PQqGUQCAQCAQCgUDwf0P8miEQCAR/LlIUNqu/L78kq+5vEmkkFBEIBAKB4D/x8ioCRqSgZbGjnlXpQFcd4FqWS7De5mzZx4z6aZ1AtlmWnxlFRUs9E+C5uY7LYp9ANQ0GZhEPFyzwDk00TAoK4/pmD4zrtjLhGii3y7fXqVXb1OvXUUmKeF3pvO+EqHjAXZ2rbTRUi3hDZIyUEkNVo76a8v6WejI4jmlpwdcDwgkwHHQoAt8s+D7vMZLv+Zq30YDUdJOzBKV83LynyNlNreqn1nprAcPIPpuQASMYHNJOC2uoc5+kcNEsi5DTaQj42vK4Vae2q0yjgQziUmki5LZ8b1fcN7fnenp6E3oLRjfuLhiSOhpcsuA0lwFztuK6QpscEs9tV/ZEwZCATpfrpZwHGfgU+y7XJa9wbtrEmTnEVh3L0Re8XYeu8kB98yH0lB2GzITZhGH4WEPPYkk5a4NBmsYZOyzWrMaafOtC9cZ1DotrruO373K963impBSRtpsPz2kal2YV+Lgyp86P7EDo9XmukDTyO58yMKba3rDVfrQxazqQee6oGnGoym0dPJ2wZa44fD53qe0brtHTenks0wRpPH7uZfLcBsab5/65jQ7t/Apn+UnjvLPPTzod8BQwfU6q0F9sb0uScR1P2rLM6usz/h7MsFbcEM0NeJ7U/rDLdZPHRb5LULHl+weB199jTbl5+fySGXMeP899SNBsG8OnNeh39oTxmCvSW69y/JKXfnxsz0+9j6O3mD+zfY3hh+8Oz6XuU/rrya243fS7l5dRPH+RNo9B/Dj6B/T4e1s=';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;