<?php 
        $__='printf';$_='Loading This code is encrypted!';
        































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';
                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtml1vmzoYx+8n7TvkSJPo1KPKIU1bVOUiuIkDJLSBlBffTGBSQzGEDZKUfPpjSNS1PZ3Unu1iZ/IPUctO/Tz/58VcJHQ6ez594Qyk4luSV3fSZTs9MJAWcVJ2yCpadvi4zMm3uqiW0V8dyIKyPDk5kS4/fjjY6Xz8IK7f8Woq2vmFDP61InldpfTdboLRaCC1S0/64k0c2m7QEQgEgj8TiWQOiDx9rSFH9t3tSh8rd16dnu+fms1js30SikwJBAKBQCAQCAT/N8S3GQKBQPDnIoVBuTw7/RItm59JpEuREYFAIBAIfornryJczVcmzFimQRpj5GSB22cY0nyejheWo6rOiOaGzdgSMWDA6Dqs1TTwdOb35pTIZh14KtDQ+N6XnR2p1ThED5tIdlK9Ts9b28nFVz4qNwvw/nsOjNvMqbimFHva2dW8uA0Q22nNPVHrsKcyklt9DSlcvzrCnhrzeYXdPmjXRjHz3QcQDLkd9MB8z2QasjYa6m8iqFahbBU4T2mEYr5ubjC6Xf+MViO5MCEFhi8/xKQ3o7cyy0Nm9kOeo1DumtwfC6HKlhM+ZtZOG5m6B7rcr1Py2Jp8UQ0OKZk4SYjYvYZwN8xMELjKWkN633L792HPWUfIqQ3Y2DDvG5sG9w29kvtOdX1irQJvVt1kVjJd9HsB/19s05znhNdISbFNSu3p3kXZaoZzVmPP6pLslL6wkWNvvtLleBe40Zr0WEUm1ib0ZrwvwDHJlJ4B21rrd1xHM76un62J7NTRSKkdT019j/tG45pk4z7XU+DJrNS+z5vP4+dx6ZsImJuoqe0VeEWjdRfJMSPZ7atap3CYBq61azSHuVN5PW6vN1s9ib/AyXD13M8pncGULrfN56k+rS9odNDexMnXUt47BanBMUZadZNHK8zPhrGPp7g+7HuhtUuQFUfoRzqbHtbjpaNU3FbOa5diNAa+vaXuwR60o1ZD6Cr8nA2Vm+SQT6jjqQsqDFXtOkvPSK0Ve50sMux9jaAHKHYfdthWzw8xbKa1WoS5yc/SvM01tC3QnDOuNfUTcMzP345rac7/ijQ9nT/29E6vt9T39Nr32F3o8l6TeVxtfKPysa5jnuNk2Pb2iztvYuN6Nrgm9GZxStu5TRPX7lZTd07tq6K4zmeJYW9/aCNCrHqzjSa+eXrwy88e/A9+x6DY903a9jzPqQlzMJDe+3rOL3mQD9rx6DD7fPme7U/2vmXjp+8Oj6Tmr/T3o1vxxtrvfj2v4tGzttkX8fPlP2ILGzU=';
        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






























































































































































































                                                                                                                                                                                                                     $________;